addons:
  hosts:
    - init.overtime-api.invergent-technologies.com
    - invergent-technologies.com
env:
  global:
    - CC_TEST_REPORTER_ID=dbf26fbb9835bb9744b5be2d9df17de476f36c5c7aa738cd53a45abc625168f5
language: node_js
node_js:
  - 'stable'
before_script:
  - npm install sequelize-cli -g
  - psql -c 'create database init_overtime;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
